### ISSUE TITLE
Where can I find my Gnosis Safe related addresses?

### ISSUE THREAD

**Issue by eightyfive** [folia-app/eip-2929#1]
Hi,

I wonder what do these addresses correspond to:

- admin gnosis safe proxy address ?
- proceedsRecipient gnosis safe proxy address ?
- gnosis safe master address ?

Are they specific per Gnosis Safe ?

In this article they say we should whitelist "the receiving Safe and the address of the Safe singleton".

Also what should I put in `storageKeys` ?

Thanks a lot.

**Comment by eightyfive** [comment]
I'm also wondering what node provider did you use to execute the Tx? (Infura? Alchemix? Through Metamask? Custom?...)

**Comment by eightyfive** [comment]
Answering my own question (well, I think so):

- admin gnosis safe proxy address: Admin account calling the `endAuction` method
- proceedsRecipient gnosis safe proxy address: Another Gnosis safe address where the funds were sent to
- gnosis safe master address: The Gnosis safe singleton address (known at safe creation)

Basically whitelist all addresses involved in the Tx. So, the destination addresses (the Gnosis Safe Vaults) _as well as_ the address calling the smart contract method (that's what I was missing).

Not too sure about the `storageKeys` thingy, so I just did put `0x0000000000000000000000000000000000000000000000000000000000000000` for all addresses but the singleton one.

Hope this helps !

**Comment by ihorbond** [comment]
Thanks @eightyfive this was def helpful. For the 

- gnosis safe master address (singleton address)

can be found here depending on your version of the safe
https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe_l2.json
